[project]
name = 'Decentralized-Advertising-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.advertiser-verification]
path = 'contracts/advertiser-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.publisher-verification]
path = 'contracts/publisher-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
